name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: krishna016016/dockerangular:latest
          push: true
          file: ./Dockerfile
          context: .

      - name: Log in to Local Docker Registry
        run: |
          echo "docker" | docker login --username "docker" --password-stdin localhost:5000

      - name: Tag and push Docker image to Local Registry
        run: |
          docker tag krishna016016/dockerangular:latest localhost:5000/dockerangular:latest
          docker push localhost:5000/dockerangular:latest

      - name: Deploy to Local Machine
        run: |
          docker run -d -p 8080:80 localhost:5000/dockerangular:latest
