name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: krishna016016/dockerangular:latest
          push: true
          file: ./Dockerfile
          context: .

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       
      - name: Deploy to Local Machine      
        run: |
          ssh -o StrictHostKeyChecking=no admin@192.168.29.84 "powershell.exe -Command \"
          docker pull krishna016016/dockerangular:latest; 
          docker stop deploydockerhub -ErrorAction SilentlyContinue;
          docker rm deploydockerhub -ErrorAction SilentlyContinue;
          docker run --name deploydockerhub -d -p 8080:80 krishna016016/dockerangular:latest\""
